<?php

declare(strict_types=1);

/**
 * Generates docs/BUSINESS_LOGIC_DEPENDENCIES.md based on class-level imports.
 *
 * Source scopes:
 * - app/
 * - src/Modules/
 *
 * Internal dependencies considered:
 * - App\*
 * - Modules\*
 */

$projectRoot = dirname(__DIR__);
$outputFile = $projectRoot.'/docs/BUSINESS_LOGIC_DEPENDENCIES.md';
$sourceRoots = [
    $projectRoot.'/app',
    $projectRoot.'/src/Modules',
];

/** @var array<string, array{file:string,deps:array<int,string>}> $classMap */
$classMap = [];

foreach ($sourceRoots as $root) {
    $iterator = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($root, FilesystemIterator::SKIP_DOTS)
    );

    /** @var SplFileInfo $file */
    foreach ($iterator as $file) {
        if ($file->getExtension() !== 'php') {
            continue;
        }

        $path = $file->getPathname();
        $content = file_get_contents($path);
        if ($content === false) {
            continue;
        }

        $namespace = extractNamespace($content);
        $className = extractClassName($content);

        if ($namespace === null || $className === null) {
            continue;
        }

        $fqn = $namespace.'\\'.$className;
        $deps = extractInternalDependencies($content, $fqn);

        $classMap[$fqn] = [
            'file' => relativePath($path, $projectRoot),
            'deps' => $deps,
        ];
    }
}

ksort($classMap);

/** @var array<string, array<string, true>> $moduleGraph */
$moduleGraph = [];

foreach ($classMap as $sourceClass => $meta) {
    $sourceModule = resolveModuleName($sourceClass);
    $moduleGraph[$sourceModule] = $moduleGraph[$sourceModule] ?? [];

    foreach ($meta['deps'] as $dep) {
        $depModule = resolveModuleName($dep);
        if ($depModule === $sourceModule) {
            continue;
        }
        $moduleGraph[$sourceModule][$depModule] = true;
    }
}

ksort($moduleGraph);

$date = gmdate('Y-m-d H:i:s\\Z');

$lines = [];
$lines[] = '# Business Logic Dependencies';
$lines[] = '';
$lines[] = "_Generated at: {$date} (UTC)_";
$lines[] = '';
$lines[] = '## Module Graph';
$lines[] = '';
$lines[] = '```text';
foreach ($moduleGraph as $module => $targets) {
    $lines[] = $module;
    $targetNames = array_keys($targets);
    sort($targetNames);
    foreach ($targetNames as $target) {
        $lines[] = '  -> '.$target;
    }
}
$lines[] = '```';
$lines[] = '';
$lines[] = '## Class-Level Dependencies';
$lines[] = '';
$lines[] = '```text';
foreach ($classMap as $class => $meta) {
    $lines[] = $class;
    $lines[] = '  file: '.$meta['file'];
    if ($meta['deps'] === []) {
        $lines[] = '  deps: (none)';
        continue;
    }

    foreach ($meta['deps'] as $dep) {
        $lines[] = '  -> '.$dep;
    }
}
$lines[] = '```';
$lines[] = '';
$lines[] = '## Notes';
$lines[] = '';
$lines[] = '- This file is generated by `scripts/generate_business_deps.php`.';
$lines[] = '- Regenerate with: `php scripts/generate_business_deps.php`.';
$lines[] = '- It focuses on internal business dependencies (`App\\*`, `Modules\\*`).';
$lines[] = '- Use with architecture tests in `tests/Architecture/LayerDependenciesTest.php`.';
$lines[] = '';

file_put_contents($outputFile, implode(PHP_EOL, $lines));
echo "written: {$outputFile}".PHP_EOL;

function extractNamespace(string $content): ?string
{
    if (preg_match('/^namespace\s+([^;]+);/m', $content, $matches) !== 1) {
        return null;
    }

    return trim($matches[1]);
}

function extractClassName(string $content): ?string
{
    if (preg_match('/^\s*(?:(?:final|abstract|readonly)\s+)*(?:class|interface|trait|enum)\s+([A-Za-z_][A-Za-z0-9_]*)/m', $content, $matches) !== 1) {
        return null;
    }

    return trim($matches[1]);
}

/**
 * @return array<int, string>
 */
function extractInternalDependencies(string $content, string $selfFqn): array
{
    if (preg_match_all('/^\s*use\s+([^;]+);/m', $content, $matches) === 0) {
        return [];
    }

    $deps = [];
    foreach ($matches[1] as $rawUse) {
        foreach (expandUseClause($rawUse) as $candidate) {
            $candidate = ltrim($candidate, '\\');
            if ($candidate === '' || $candidate === $selfFqn) {
                continue;
            }

            if (! str_starts_with($candidate, 'App\\') && ! str_starts_with($candidate, 'Modules\\')) {
                continue;
            }

            $deps[$candidate] = true;
        }
    }

    $result = array_keys($deps);
    sort($result);

    return $result;
}

/**
 * @return array<int, string>
 */
function expandUseClause(string $clause): array
{
    $clause = trim($clause);
    if ($clause === '') {
        return [];
    }

    if (str_starts_with($clause, 'function ') || str_starts_with($clause, 'const ')) {
        return [];
    }

    if (strpos($clause, '{') === false) {
        return [normalizeUsePart($clause)];
    }

    $prefix = strstr($clause, '{', true);
    $prefix = rtrim($prefix === false ? '' : trim($prefix), '\\');

    $inner = strstr($clause, '{');
    if ($inner === false) {
        return [normalizeUsePart($clause)];
    }

    $inner = trim($inner, '{} ');
    if ($inner === '') {
        return [];
    }

    $parts = array_map('trim', explode(',', $inner));
    $expanded = [];
    foreach ($parts as $part) {
        if ($part === '' || str_starts_with($part, 'function ') || str_starts_with($part, 'const ')) {
            continue;
        }
        $normalized = normalizeUsePart($part);
        $expanded[] = $prefix !== '' ? $prefix.'\\'.$normalized : $normalized;
    }

    return $expanded;
}

function normalizeUsePart(string $part): string
{
    $part = trim($part);
    $asPos = stripos($part, ' as ');
    if ($asPos !== false) {
        $part = trim(substr($part, 0, $asPos));
    }

    return ltrim($part, '\\');
}

function resolveModuleName(string $class): string
{
    if (str_starts_with($class, 'Modules\\')) {
        $parts = explode('\\', $class);
        return $parts[1] ?? 'Modules';
    }

    if (str_starts_with($class, 'App\\')) {
        return 'App';
    }

    return 'External';
}

function relativePath(string $path, string $root): string
{
    $normalizedPath = str_replace('\\', '/', $path);
    $normalizedRoot = rtrim(str_replace('\\', '/', $root), '/').'/';
    if (str_starts_with($normalizedPath, $normalizedRoot)) {
        return substr($normalizedPath, strlen($normalizedRoot));
    }

    return $normalizedPath;
}
